version: "3"

services:
  scheduler:
    image: python-scheduler:latest  # Change version
    container_name: python-scheduler  # Change container name
    restart: on-failure
    volumes:
      - data:/data

volumes:
  data:
    external: true
    name: data  # Change volume name
