version: "3"

services:
  scheduler:
    container_name: python-scheduler  # Change container name
    image: python-scheduler:latest  # Change version
    restart: on-failure
    environment:  # Change IDs
      PUID: 1000
      PGID: 1000
    volumes:
      - vol_data:/data

volumes:
  vol_data:
    external: true
    name: data  # Change volume name
