version: "3"

services:
  website:
    container_name: node-website  # Change container name
    image: node-website:latest  # Change version
    restart: unless-stopped
    environment:  # Change IDs
      PUID: 1000
      PGID: 1000
    volumes:
      - vol_data:/app
    ports:
      - 8080:8080  # Change host-port (HOST:CONTAINER)

volumes:
  vol_data:
    external: true
    name: data  # Change volume name
