version: "3"

services:
  website:
    image: node-website:latest  # Change version
    container_name: node-website  # Change container name
    restart: unless-stopped
    volumes:
      - data:/app
    ports:
      - 8080:8080  # Change port (HOST:CONTAINER)

volumes:
  data:
    external: true
    name: data  # Change volume name
